### ISSUE TITLE
cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by akp6031** [davidecenzato/optimalBWT#1]
Hi, I am experiencing the error below when running make. Can you give some advice?

cc    -c -o external/malloc_count/malloc_count.o external/malloc_count/malloc_count.c
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -g -c -o lib/optsais32.o lib/optSAIS.cpp 
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -g -o optsais main.cpp IOfunc.hpp computeTransform.cpp external/malloc_count/malloc_count.o lib/optsais32.o -ldl
clang: error: cannot specify -o when generating multiple output files

**Comment by davidecenzato** [comment]
Hello,

There was a problem when compiling the software with clang. I've pushed a fix that should have fixed the problem.

best,
Davide
