### ISSUE TITLE
The inverse transform of optBWT

### ISSUE THREAD

**Issue by xiaoYu0103** [davidecenzato/optimalBWT#2]
For example:
M={TGA,CACAA,AGAGT,TAA,CGAGT,CCA,TA}
optBWT(M)=TTAAAAAAAGCTTCC$GGCA$$$TCAAAGG$$$
How do I invert optBWT(M) back to M?

**Comment by davidecenzato** [comment]
Hello, I will split the answer in two. 
1) Practical answer: We currently do not provide software for inverting the optBWT in this repository. However, you can invert the optBWT by using any software that works on the BWT given in output by the BCR algorithm (example: https://github.com/giovannarosone/BCR_QS_decode).
2) Theoretical answer: You can invert the optBWT by using the LF-property as we do with the classic BWT. The algorithm employed is very similar to the backward search; the only difference is that we have n strings here, so we will need to walk over n cycles. (You can find a nice explanation of this procedure in Chapter 4 of this paper, "Lightweight algorithms for constructing and inverting the BWT of string collections" Bauer et al. 2013)

**Comment by xiaoYu0103** [comment]
Thanks, I have solved this problem through your help！
